name: Daily Penguin Prediction

on:
  schedule:
    - cron: '30 7 * * 1'  # Run at 7:30 AM UTC every day
    
  workflow_dispatch:  # Allow manual triggering

jobs:
  predict:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy requests

      - name: Fetch new data and make prediction
        run: |
          python scripts/predict.py
        
      - name: Commit and push if prediction changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add data/predictions.json index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update prediction for $(date +'%Y-%m-%d')" && git push)
